apiVersion: v1
kind: Service
metadata:
  name: devops-assistant-frontend
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: devops-assistant-frontend
  ports:
    - port: 80
      targetPort: 80
